/**
 * GitHub Repository Creation API
 * 
 * Creates a new GitHub repository with the project template.
 * Requires GitHub OAuth authentication.
 */

import { NextRequest, NextResponse } from "next/server";
import { apiError, apiSuccess, ErrorCodes } from "@/lib/api-errors";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization",
};

interface CreateRepoRequest {
  name: string;
  description?: string;
  template?: string;
  projectToken?: string;
  integrations?: Record<string, string>;
  isPrivate?: boolean;
}

export async function OPTIONS() {
  return new NextResponse(null, { status: 200, headers: corsHeaders });
}

export async function POST(request: NextRequest) {
  try {
    // Check for GitHub access token
    const authHeader = request.headers.get("Authorization");
    const githubToken = authHeader?.replace("Bearer ", "");

    if (!githubToken) {
      return apiError(
        ErrorCodes.UNAUTHORIZED,
        "GitHub authentication required",
        401,
        undefined,
        "Connect your GitHub account first by clicking 'Connect GitHub' in the configurator.",
        corsHeaders
      );
    }

    const body: CreateRepoRequest = await request.json();
    const { name, description, isPrivate = true } = body;

    if (!name) {
      return apiError(
        ErrorCodes.MISSING_FIELD,
        "Repository name is required",
        400,
        { required: ["name"] },
        "Provide a valid repository name",
        corsHeaders
      );
    }

    // Validate repo name (GitHub requirements)
    const validRepoName = /^[a-z0-9][a-z0-9-]*[a-z0-9]$|^[a-z0-9]$/i;
    if (!validRepoName.test(name)) {
      return apiError(
        ErrorCodes.INVALID_INPUT,
        "Invalid repository name",
        400,
        { name },
        "Repository name must start with a letter or number and can contain hyphens",
        corsHeaders
      );
    }

    // Create repository via GitHub API
    const createRepoResponse = await fetch("https://api.github.com/user/repos", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${githubToken}`,
        Accept: "application/vnd.github.v3+json",
        "Content-Type": "application/json",
        "User-Agent": "dawson-does-framework",
      },
      body: JSON.stringify({
        name,
        description: description || `Project generated by dawson-does-framework`,
        private: isPrivate,
        auto_init: true, // Create with README
      }),
    });

    if (!createRepoResponse.ok) {
      const errorData = await createRepoResponse.json();
      
      if (createRepoResponse.status === 422) {
        return apiError(
          ErrorCodes.INVALID_INPUT,
          "Repository name already exists",
          422,
          { github_error: errorData },
          "Choose a different repository name or delete the existing one",
          corsHeaders
        );
      }

      if (createRepoResponse.status === 401) {
        return apiError(
          ErrorCodes.UNAUTHORIZED,
          "GitHub token expired or invalid",
          401,
          undefined,
          "Reconnect your GitHub account to get a fresh token",
          corsHeaders
        );
      }

      return apiError(
        ErrorCodes.INTERNAL_ERROR,
        "Failed to create GitHub repository",
        500,
        { github_error: errorData },
        "Check your GitHub account permissions and try again",
        corsHeaders
      );
    }

    const repoData = await createRepoResponse.json();

    // Log success
    console.log(`[GitHub Repo Created] ${repoData.full_name} | ${repoData.html_url}`);

    return apiSuccess(
      {
        id: repoData.id,
        name: repoData.name,
        full_name: repoData.full_name,
        html_url: repoData.html_url,
        clone_url: repoData.clone_url,
        ssh_url: repoData.ssh_url,
        private: repoData.private,
      },
      201,
      corsHeaders
    );
  } catch (error: unknown) {
    console.error("[GitHub Create Repo Error]", error);
    const message = error instanceof Error ? error.message : "Unknown error";
    return apiError(
      ErrorCodes.INTERNAL_ERROR,
      "Failed to create repository",
      500,
      process.env.NODE_ENV === "development" ? { message } : undefined,
      "Please try again. If the issue persists, check your GitHub permissions.",
      corsHeaders
    );
  }
}

